### PR TITLE
Feature: show an invite button to registered students without teams.

### LINKED ISSUE #537: No option to invite team member
I have received a few messages from students that they are unable to find the option to invite team member. 

This seems to start happening after we changed the pending flags of the students from true to false. 

One example is the following student: 
http://nusskylab-dev.comp.nus.edu.sg/users/1254

Could anyone help to check?

### PR DESCRIPTION
**Pull request by njyjn**
This resolves #537.

Registered students (pending flag false) are now given the appropriate invite teammate button.

screen shot 2017-07-15 at 11 00 37 pm

### CODE REVIEW

**Comment by potatowagon** [comment]
Hello, I've fetched this PR and sync vagrant to load new changes, but I'm not to sure how to reach that page, this is what I see

capture


removing myself as an admin yields this:
capture1

need help, thanks! ^^

**Comment by knmnyn** [comment]
@potatowagon this is a problem with your Skylab not having any users that are useful for checking the status of system.  You'll need to add some fixture users.  Perhaps we should delay this until the team has some fixture data in place.

Also it is a problem that the current year is 2018.  You may need to update your system to include 2018 students and teams.  I will branch that as a separate issue.

**Comment by knmnyn** [comment]
Cross reference #560

**Comment by potatowagon** [comment]
Hello

Previewed this as a student from fixture data but bumped into "Registration for 2017 has closed"

Prof Kan pointed out earlier "You may need to update your system to include 2018 students and teams."
May I know how to do that?

This happens when setting the cohort to 2017 to bypass "Registration for 2017 has closed"

screenshot 26

The message surrounding invite team member seems different from that in the file changes, so I guess I am looking at the wrong thing

**Comment by knmnyn** [comment]
That's fine if you manually set the cohort to 2017.  By default I think Skylab gets the cohort via time.now.year() or something similar based on the system clock.

**Comment by chowyb** [comment]
#585 was just merged in, which should help address the "Registration for 2017 has closed" issue, since it can be toggled from the admin homepage now.

**Pull request merged**
