### PR TITLE
#656 Replace team image if not found

### PR DESCRIPTION
**Pull request by Wklee96**
## Status
**HOLD**
Not sure why travis fails 

## Migrations
NO

## Description
To replace team image if not found 

## Todos
- [ ] Tests

*

### CODE REVIEW

**Comment by Wklee96** [comment]
I can't get the secret key working with DummyToken.sh so I had to manually paste the secret keys into these files and it worked. If I add it in to these commits will there be a problem?

**Comment by yhchong** [comment]
"added method to verify poster_link",  "changed condition" and "added comments" is good but you need to undo the rest of the commits that are not necessary. Thanks!

**Comment by yhchong** [comment]
> I can't get the secret key working with DummyToken.sh so I had to manually paste the secret keys into these files and it worked. If I add it in to these commits will there be a problem?

You try git branch to master, make sure there are no changes from master. Then vagrant halt, vagrant destroy and vagrant up again. It should be able to set everything up (init the database and stuff). Let me know! You can refer to the Wiki on how to do a totally fresh rebuild on vagrant. Let me know if it works! Thanks!

**Comment by yhchong** [comment]
Dude, you are not supposed to be merging into master.

**Comment by Wklee96** [comment]
I'm so sorry I accidentally pushed into the master, how do I fix this?

**Comment by yhchong** [comment]
Okay. I have just reverted the change. Please delete and reclone your nusskylab directory. 

The solution for #656 Replace team image if not found #658 is in 

- app/models/team.rb 
- app/views/public_views/public_projects/_public_teams_table.html.erb 

only right?

**Comment by Wklee96** [comment]
Yes only this two files. I'm really sorry for pushing into master. Will be more careful

**Comment by Wklee96** [comment]
I have reverted the commits in issue#656 branch and passed travis, do I create a new PR?

**Comment by yhchong** [comment]
No problem! Yes, please. Create PR!

**Pull request merged**
