### PR TITLE
Making projects clickable

### PR DESCRIPTION
**Pull request by le-minhphuc**
I have adjusted the appearance of project listing view. Currently, clicking on the team's name leads to the same page. If the layout looks fine, I'll add a pop-up box like in http://isteps.comp.nus.edu.sg/event/7th-steps/modules

### CODE REVIEW

**Comment by knmnyn** [comment]
Hi Phuc:

Thanks for doing this!  The travis build reports a failure with the devise
secret key.  You may want to refer to the travis CI log.

https://travis-ci.org/nusskylab/nusskylab/builds/183584479

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by knmnyn** [comment]
Note this has secret information on the public website, we may have to find
a way to drop this information from public view.

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by le-minhphuc** [comment]
Hi Prof Kan, 
I have fixed the problem with Travis Build. May I check with you about the secret information being revealed in public view as I'm not sure about the info that you are referring to - is it the secret key, or is it something else?

**Comment by knmnyn** [comment]
Hi Phuc:

Ok, so far looks good.  You have the right idea, but we need to have the
links provide new pages so that the search engine can index them.

If the pop-up does something like that (generates a new URL that is
indexable by a search engine), your idea is fine.

When you are able to fix it, please refer to Issue #473 to close the issue.

Thanks!


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Pull request merged**
