### PR TITLE
Address issue #492

### PR DESCRIPTION
**Pull request by le-minhphuc**
#492

### CODE REVIEW

**Comment by le-minhphuc** [comment]
Not sure why the build failed ... It works fine on my fork though
(https://cloud.githubusercontent.com/assets/15699157/22137610/04644d70-df17-11e6-958b-1185199c74ea.png)

**Comment by knmnyn** [comment]
Seems again a problem with the Devise secret key.

Please try to resolve this before I try to merge.

Thanks!


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by knmnyn** [comment]
HI @le-minhphuc, with your other branch, do you want to have this branch deleted?
Perhaps you can clean up so that it's clear that I should attempt to merge the other branch instead of this one?

Please assign other team members to review your PR.  All, please record your hours for doing so.

Thanks!

**Comment by le-minhphuc** [comment]
Yes prof @knmnyn , I would like to have this branch deleted. I'm going to assign Justin/Weng Kiat to review my PR.

**Pull request closed without merging**
