### PR TITLE
Thredded forum integration

### LINKED ISSUE #488: Investigate forums implemented using Ruby on rails
Check on their interface (especially with respect to db tables).
Check whether it's easy to embed UI wise.
Check whether users can be synchronized with the current Devise role users.

List alternatives directly here, in the issue's thread.

### PR DESCRIPTION
**Pull request by njyjn**
Resolves #488 [WIP]

## Todo
- [x] Installed forum engine as add-on app
- [x] Integrated with user database to show post count and recent posts (at /users/xxx)  
- [x] Navigation bar points to /forum for non-public users
- [x] Theme integration (toughest!!!)
- [x] Theme fine tuning
- [ ] Make forum navbar more intuitive (try to include a back button)
- [ ] Etc. (add)

## Notes
- Gemfile was updated to include `thredded` (0.9.3) and `backport_new_renderer` (1.0.0). Upgraded `jquery-rails` to (4.2.1)
- Emoji support added locally.
- Presently only admins may moderate the forum.
- Mobile responsivity suspected. 

Screenshot as at 30/1:

screen shot 2017-01-30 at 01 46 21

### CODE REVIEW

**Comment by knmnyn** [comment]
Seems like the four crucial elements for the forum system are in.
Is this ready for integration, or do we need to wait for the 3 remaining checks?

If you think it's ready we should air it for the Orbital registration period so that others can discuss using the forum board to possibly find teammates, etc.

**Comment by njyjn** [comment]
@knmnyn No worries, but I need to resolve some merge conflicts first. I'll let you know when we can go live, which would be by this evening. Thanks!

**Comment by knmnyn** [comment]
Great, thanks very much!

Looking forward to seeing your hard work, live.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by njyjn** [comment]
Ok, conflicts have been resolved. Ready for merging.

**Comment by knmnyn** [comment]
Integration leaves 502 error.  Details shortly.

**Comment by njyjn** [comment]
@knmnyn Prof we need to do a `bundle install` serverside to install the forum's new dependencies.

**Comment by knmnyn** [comment]
@njyjn This was done.  The deploy script does the bundle install and invokes any pending db schema migrations.

**Comment by njyjn** [comment]
Getting an error with the `/forum` route. A few more steps to take:

1. `rails generate thredded:install`
2. `rake thredded:install:emoji`
3. `rake thredded:install:migrations db:migrate db:test:prepare`

As documented here https://github.com/nusskylab/nusskylab/wiki/Thredded-Setup-Guide. Had to do it on my local system too.

**Comment by knmnyn** [comment]
=== puma startup: 2017-03-06 21:36:37 +0800 ===
WARN: Unresolved specs during Gem::Specification.reset:
      minitest (~> 5.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
2017-03-06 21:36:40 +0800: Rack app error: #<RuntimeError: Missing `secret_token` and `secret_key_base` for 'production' environment, set these values in `config/secrets.ym
l`>
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/application.rb:534:in `validate_secret_key_config!'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/application.rb:246:in `env_config'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/engine.rb:514:in `call'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/application.rb:164:in `call'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puma-2.11.3/lib/puma/configuration.rb:51:in `call'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puma-2.11.3/lib/puma/server.rb:507:in `handle_request'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puma-2.11.3/lib/puma/server.rb:375:in `process_client'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puma-2.11.3/lib/puma/server.rb:262:in `block in run'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puma-2.11.3/lib/puma/thread_pool.rb:104:in `call'
/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/puma-2.11.3/lib/puma/thread_pool.rb:104:in `block in spawn_thread'


Ok will try.  The above seem to the the relevant errors from shared/log/puma.stderr.log .

**Comment by knmnyn** [comment]
[root@nusskylab-dev-i log]# rails generate thredded:install
Running via Spring preloader in process 4210
    conflict  config/initializers/thredded.rb
Overwrite /var/www/nusskylab/config/initializers/thredded.rb? (enter "h" for help) [Ynaqdh] d
  # frozen_string_literal: true
  # Thredded configuration
  
  # ==> User Configuration
  # The name of the class your app uses for your users.
  # By default the engine will use 'User' but if you have another name
  # for your user class - change it here.
  Thredded.user_class = 'User'
  
  # User name column, used in @mention syntax and should be unique.
  # This is the column used to search for users' names if/when someone is @ mentioned.
- Thredded.user_name_column = :user_name
+ Thredded.user_name_column = :name
  
  # User display name method, by default thredded uses the user_name_column defined above
  # You may want to use :to_s or some more elaborate method
  # Thredded.user_display_name_method = :to_s
  
  # The path (or URL) you will use to link to your users' profiles.
  # When linking to a user, Thredded will use this lambda to spit out
  # the path or url to your user. This lambda is evaluated in the view context.
  Thredded.user_path = lambda do |user|
    user_path = :"#{Thredded.user_class.name.underscore}_path"
    main_app.respond_to?(user_path) ? main_app.send(user_path, user) : "/users/#{user.to_param}"
  end
  
  # This method is used by Thredded controllers and views to fetch the currently signed-in user
  Thredded.current_user_method = :"current_#{Thredded.user_class.name.underscore}"
  
  # User avatar URL. rb-gravatar gem is used by default:
  Thredded.avatar_url = ->(user) { Gravatar.src(user.email, 128, 'mm') }
  
  # ==> Permissions Configuration
  # By default, thredded uses a simple permission model, where all the users can post to all message boards,
  # and admins and moderators are determined by a flag on the users table.
  
  # The name of the moderator flag column on the users table.
  Thredded.moderator_column = :admin
  # The name of the admin flag column on the users table.
  Thredded.admin_column = :admin
  
  # Whether posts and topics pending moderation are visible to regular users.
  Thredded.content_visible_while_pending_moderation = true
  
  # Whether users that are following a topic are listed on topic page.
  Thredded.show_topic_followers = false
  
  # This model can be customized further by overriding a handful of methods on the User model.
  # For more information, see app/models/thredded/user_extender.rb.
  
  # ==> Ordering configuration
  
  # How to calculate the position of messageboards in a list:
  # :position            (default) set the position manually (new messageboards go to the bottom, by creation timestamp)
  # :last_post_at_desc   most recent post first
  # :topics_count_desc   most topics first
  Thredded.messageboards_order = :position
  
  # ==> Email Configuration
  # Email "From:" field will use the following
  # Thredded.email_from = 'no-reply@example.com'
  
  # Emails going out will prefix the "Subject:" with the following string
  # Thredded.email_outgoing_prefix = '[My Forum] '
  
  # ==> View Configuration
  # Set the layout for rendering the thredded views.
- #Thredded.layout = 'thredded/application'
+ Thredded.layout = 'thredded/application'
- Thredded.layout = 'layouts/application'
  
  # ==> Post Content Formatting
  # Customize the way Thredded handles post formatting.
  
  # Change the default html-pipeline filters used by thredded.
  # E.g. to replace default emoji filter with your own:
  # Thredded::ContentFormatter.after_markup_filters[
  #   Thredded::ContentFormatter.after_markup_filters.index(HTML::Pipeline::EmojiFilter)] = MyEmojiFilter
  
  # Change the HTML sanitization settings used by Thredded.
  # See the Sanitize docs for more information on the underlying library: https://github.com/rgrove/sanitize/#readme
  # E.g. to allow a custom element <custom-element>:
  # Thredded::ContentFormatter.whitelist[:elements] += %w(custom-element)
  
  # ==> User autocompletion (Private messages and @-mentions)
- Thredded.autocomplete_min_length = 2 # lower to 1 if have 1-letter names -- increase if you want
+ # Thredded.autocomplete_min_length = 2 lower to 1 if have 1-letter names -- increase if you want
  
  # ==> Error Handling
  # By default Thredded just renders a flash alert on errors such as Topic not found, or Login required.
  # Below is an example of overriding the default behavior on LoginRequired:
  #
  # Rails.application.config.to_prepare do
  #   Thredded::ApplicationController.module_eval do
  #     rescue_from Thredded::Errors::LoginRequired do |exception|
  #       @message = exception.message
  #       render template: 'sessions/new', status: :forbidden
  #     end
  #   end
  # end
  
  # ==> View hooks
  #
  # Customize the UI before/after/replacing individual components.
  # See the full list of view hooks and their arguments by running:
  #
  #     $ grep view_hooks -R --include '*.html.erb' "$(bundle show thredded)"
  #
  # Rails.application.config.to_prepare do
  #   Thredded.view_hooks.post_form.content_text_area.config.before do |form:, **args|
  #     # This is called in the Thredded view context, so all Thredded helpers and URLs are accessible here directly.
  #     'hi'
  #   end
  # end
  
  # ==> Topic following
  #
  # By default, a user will be subscribed to a topic they've created. Uncomment this to not subscribe them:
  #
  # Thredded.auto_follow_when_creating_topic = false
  #
  # By default, a user will be subscribed to (follow) a topic they post in. Uncomment this to not subscribe them:
  #
  # Thredded.auto_follow_when_posting_in_topic = false
  #
  # By default, a user will be subscribed to the topic they get @-mentioned in.
  # Individual users can disable this in the Notification Settings.
  # To change the default for all users, simply change the default value of the `follow_topics_on_mention` column
  # of the `thredded_user_preferences` and `thredded_user_messageboard_preferences` tables.
  
  # ==> Notifiers
  #
  # Change how users can choose to be notified, by adding notifiers here, or removing the initializer altogether
  #
  # default:
- Thredded.notifiers = [Thredded::EmailNotifier.new]
+ # Thredded.notifiers = [Thredded::EmailNotifier.new]
  #
  # none:
  # Thredded.notifiers = []
  #
  # add in (must install separate gem (under development) as well):
  # Thredded.notifiers = [Thredded::EmailNotifier.new, Thredded::PushoverNotifier.new(ENV['PUSHOVER_APP_ID'])]
- 
- 
- # to allow you to not to have to add `main_app` before every path helper 
- # when embedding Thredded within a main-app supplied layout (with navbar and links to the main_app)
- 
- Rails.application.config.to_prepare do
-   Rails.application.reload_routes!
-   thredded_methods = (Thredded::Engine.routes.url_helpers.methods + Thredded::UrlsHelper.instance_methods)
-     .select { |s| s.to_s.ends_with?("_path", "_url") }
-   main_app_delegator = Module.new do
-     Rails.application.routes.url_helpers.methods
-       .select { |m| m.to_s.ends_with?('_path', '_url') }
-       .reject { |m| thredded_methods.include?(m).tap { |r| Rails.logger.warn "ignoring conflict: #{m}" if r } }
-       .each{ |method_name| send(:define_method, method_name) {|*args| main_app.send(method_name, *args)} }
-   end
-   ::Thredded::ApplicationController.helper main_app_delegator
- end
Retrying...
Overwrite /var/www/nusskylab/config/initializers/thredded.rb? (enter "h" for help) [Ynaqdh] q
Aborting...

**Comment by knmnyn** [comment]
Ok, seems to work now.  Please test.

**Comment by njyjn** [comment]
Works on my end.

screen shot 2017-03-07 at 23 42 42

**Pull request merged**
