### PR TITLE
Fix issues #513 (User roles tab), #516 (Hide sample staff data)

### PR DESCRIPTION
**Pull request by njyjn**
The fix addresses the following:

- Makes the user profile page more pleasant to the eye by resizing each element. Gravatar is no longer too large.
- Forum contributions get their own panel box.
- User roles tab fix (#513)
- User informed that Gravatar is used for profile picture.
- Hides sample staff data ending with `@example.com` (#516)

This PR assumes `add-thredded` (#508) has already been merged, as it is a dependency.

### CODE REVIEW

**Comment by knmnyn** [comment]
Hi @njyjn @le-minhphuc Can you try to resolve the two conflicts on Gemfile.lock and on show.html.erb before these edits are merged?  Thanks!

**Comment by njyjn** [comment]
The conflicts have been resolved :-)

**Comment by njyjn** [comment]
Note: Accessing skylab returns a 502 error. Is this a server side or application side error?

**Comment by knmnyn** [comment]
@njyjn This was from the previous merge for the forum.  The rest of skylab is functional currently.  I will try to give some detail on the errors in the appropriate PR thread. #508

**Pull request merged**
