### PR TITLE
Add link into Nav bar and check for matric number validity

### PR DESCRIPTION
**Pull request by wengkiat**
1. Add a link in the nav bar for logged in users to see projects and staff (these links are already in the logged out zone)

2. Update the user fields to add Matric Number and Home Faculty fields. Implement a validation check for Matric Numbers. Allow these to be populated in the User Settings, under "edit user settings" in the 'gear' menu after logging in.

### CODE REVIEW

**Comment by knmnyn** [comment]
Hi @wengkiat , your branch has conflicts.  Can you fix them first?

**Comment by knmnyn** [comment]
Ok, I've tried to fix the conflicts.  It was due to another check-in earlier.

**Comment by wengkiat** [comment]
Hi Prof Kan,

 

Yeap! The conflict was due to a new field slack id, which I did not pull when I started on the task.

 

May I know if there are any other issues with the task assigned?

 

-- 

Regards,

Weng Kiat

**Comment by knmnyn** [comment]
not now.  I have a db:migration problem that I need to solve before I can deploy your fix.
I'll let you know hopefully soon.

**Comment by knmnyn** [comment]
When testing, when the matric number is valid the system still complains.  The entry is not blank.

image

The matric number is required of students and advisors and tutors, but not of other roles.  Can you help fix, or better yet, create another issue and solve this additional functionality.

**Comment by knmnyn** [comment]
Hmm.  The files and the commit don't seem to do anything with the nav bar too.  
Perhaps also fix this.

**Comment by wengkiat** [comment]
@knmnyn , the failure is due to when you resolved the pull request, the matric number field is left out in the def user_params method as shown below, so it will not update and always reflect blank. 

def user_params(generate_pswd = false)
    user_ps = params.require(:user).permit(
      :user_name, :email, :uid, :provider, :slack_id, :github_link, :linkedin_link,
      :blog_link, :program_of_study, :self_introduction)
    user_ps[:password] = Devise.friendly_token.first(8) if generate_pswd
    user_ps[:provider] = user_ps[:provider].to_i
    user_ps[:program_of_study] = user_ps[:program_of_study].to_i
    user_ps
  end

**Pull request merged**
