### PR TITLE
Add view in students table displaying registration date and time.

### LINKED ISSUE #527: Sort order and date of registration for the students page?
I can't seem to figure out the sort order of the students page. It does not seem to be based on the name or date of registration. 

Is it possible to show the date of registration (e.g., the date on which the registration form was completed) on the page? Otherwise, it is quite difficult to figure out which are the new students and which students should be accepted.

### PR DESCRIPTION
**Pull request by njyjn**
This allows admin to see when student registered.

Partially resolves #527, but sort functionality has yet to be implemented (still investigating why tables are not displaying sort arrows). Merge now if @zhaojin42 requires. Thanks!

### CODE REVIEW

**Comment by zhaojin42** [comment]
Great. Thanks a lot! 

Please merge.

**Comment by njyjn** [comment]
Ok, it has been merged. A pull on the server may be necessary for changes to take effect.

**Comment by zhaojin42** [comment]
I checked just now that the changes have not taken effect. 

Could anyone help to pull on the server? Thanks a lot!

**Comment by njyjn** [comment]
Hi Jin, I do not have access to the server, if you'd like you could pass me the creds privately? Thanks.

**Comment by zhaojin42** [comment]
I thought I have the creds but they didn't work when I tried them just now.  *_* 

We will need to get @knmnyn to help on this.

**Comment by knmnyn** [comment]
Ok, pulled and merged but with errors on data migration.


W, [2017-04-03T22:22:17.967475 #11562]  WARN -- : ignoring conflict:
root_path

W, [2017-04-03T22:22:17.967661 #11562]  WARN -- : ignoring conflict:
user_path

W, [2017-04-03T22:22:17.967891 #11562]  WARN -- : ignoring conflict:
root_url

D, [2017-04-03T22:22:21.612443 #11562] DEBUG -- :
*ActiveRecord::SchemaMigration
Load (82.1ms)*  *SELECT "schema_migrations".* FROM "schema_migrations"*

I, [2017-04-03T22:22:21.696887 #11562]  INFO -- : Migrating to
AddIndexToUsernameInUsersForThredded (20170307170913)

D, [2017-04-03T22:22:21.708523 #11562] DEBUG -- :   * (0.1ms)*  BEGIN

== 20170307170913 AddIndexToUsernameInUsersForThredded: migrating
=============

D, [2017-04-03T22:22:22.034920 #11562] DEBUG -- :   *SQL (279.3ms)*  *CREATE
UNIQUE INDEX users_user_name_lower ON "users" (LOWER("user_name")
text_pattern_ops)*

E, [2017-04-03T22:22:22.034998 #11562] ERROR -- : PG::UniqueViolation:
ERROR:  could not create unique index "users_user_name_lower"

DETAIL:  Key (lower(user_name::text))=(thenaesh s/o n elango) is duplicated.

: CREATE UNIQUE INDEX users_user_name_lower ON "users" (LOWER("user_name")
text_pattern_ops)

D, [2017-04-03T22:22:22.035392 #11562] DEBUG -- :   * (0.3ms)*  ROLLBACK

rake aborted!

StandardError: An error has occurred, this and all later migrations
canceled:


PG::UniqueViolation: ERROR:  could not create unique index
"users_user_name_lower"

DETAIL:  Key (lower(user_name::text))=(thenaesh s/o n elango) is duplicated.

: CREATE UNIQUE INDEX users_user_name_lower ON "users" (LOWER("user_name")
text_pattern_ops)/var/www/nusskylab/db/migrate/20170307170913_add_index_to_username_in_users_for_thredded.rb:3:in
`change'

ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  could not
create unique index "users_user_name_lower"

DETAIL:  Key (lower(user_name::text))=(thenaesh s/o n elango) is duplicated.

: CREATE UNIQUE INDEX users_user_name_lower ON "users" (LOWER("user_name")
text_pattern_ops)

/var/www/nusskylab/db/migrate/20170307170913_add_index_to_username_in_users_for_thredded.rb:3:in
`change'

PG::UniqueViolation: ERROR:  could not create unique index
"users_user_name_lower"

DETAIL:  Key (lower(user_name::text))=(thenaesh s/o n elango) is duplicated.

/var/www/nusskylab/db/migrate/20170307170913_add_index_to_username_in_users_for_thredded.rb:3:in
`change'

Tasks: TOP => db:migrate

(See full trace by running task with --trace)

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Pull request merged**
