### PR TITLE
Add ignition poster and video link to teams page

### LINKED ISSUE #569: Add Ignition (Milestone #0) into the team page
For each team, we should store the slide they have submitted and the video of their ignition presentation (if available).

### PR DESCRIPTION
**Pull request by lincredibleJC**
Fixes #569 
Added fields to teams and its views
Users, advisors and admins are able to edit Poster Link
Advisors and admins are able to edit Poster Link

### CODE REVIEW

**Comment by chowyb** [comment]
Travis appears to be complaining about pending migrations (under travis-ci/push). You may need to change the following line (similar to #588):

https://github.com/nusskylab/nusskylab/blob/0ebf58ee2aac55e875fc06380890eacf62d12e54/db/schema.rb#L14

Since both PRs touch different parts of the schema, I believe there shouldn't be a need to worry about conflicting migrations.

Also, I'd just like to check if you're planning on adding anything else to this PR, since I'm currently assuming this is still a work in progress, going by the PR description.

**Comment by lincredibleJC** [comment]
@chowyb Yes, I'm still working on it. I think that this line was not changed because I did not generate the migration file with rails. I'll update it.

**Comment by chowyb** [comment]
@lincredibleJC any updates on this PR?

**Comment by lincredibleJC** [comment]
@chowyb I will be adding logic to automatically save the link submitted to the team's page.

**Comment by lincredibleJC** [comment]
@chowyb It seems that each survey is accessible through each student's view evaluations forms page. I realised that having a separate submission and survey template to get the video link for the student will be confusing to the student as not much needs to be done for lift off and both the survey and milestone ask for links to the poster and video.

Hence, I'll be removing milestone 0 and it's surveys and just making it possible for students to add and edit their team's links in the team's page

**Comment by knmnyn** [comment]
Agreed with this.  This would be better for the (very) basic requirements for dealing with Liftoff.

**Comment by lincredibleJC** [comment]
@knmnyn I've made it such that only students and admins can edit the links, would you want advisors to also be able to edit the links?

**Comment by knmnyn** [comment]
Hi Jiachao:

Sure, that would be good.  I think potentially advisors can help add
information during Liftoff, in case students can't figure out how to access
Skylab.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by lincredibleJC** [comment]
@knmnyn Alright, that has been added in. This feature should be ready.

@chowyb I've made a mistake by adding a Milestone 0 and Survey template under that milestone in production. Do you mind helping me remove that survey template and milestone?

**Comment by lincredibleJC** [comment]
A future PR will be done to update the relevant links on the teams page on updating the individual submissions

**Pull request merged**
